
- builder:
    name: copy-update-source
    builders:
      - shell: |
            mv /opt/git/libvirt $WORKSPACE
            cd libvirt
            git clean -f -x
            git fetch -f --recurse-submodules=yes \
                                       origin {branch}
            git checkout FETCH_HEAD

- builder:
    name: test-libvirt
    builders:
      - shell: |
            cd libvirt
            ./autogen.sh --system
            make
            sudo make install
            libvirtd --version
            sudo libvirtd -d
            virsh list --all

- job-template:
    name: smoke-libvirt-{branch}
    node: trusty-label || dib-trusty-label
    builders:
      - copy-update-source:
          branch: '{branch}'
      - test-libvirt
    publishers:
      - email:
          recepients: 'eantyshev@virtuozzo.com'
        

- project:
    name: libvirt
    branch:
      - master
      - v1.3.1-maint
    jobs:
      - smoke-libvirt-{branch}
